# Numpy 2

## Creation Function

In [1]:
import numpy as np

c = np.arange(0, 10, 0.5)
c.reshape(-1,2)

array([[0. , 0.5],
       [1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5],
       [5. , 5.5],
       [6. , 6.5],
       [7. , 7.5],
       [8. , 8.5],
       [9. , 9.5]])

In [2]:
np.zeros((10,), int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
d = np.arange(9).reshape(3,3)
np.diag(d)

array([0, 4, 8])

In [5]:
np.diag(d, 1)

array([1, 5])

In [6]:
uniform = np.random.uniform(0,1,10).reshape(2,5)
normal = np.random.normal(0,1,10).reshape(2,5)
print(uniform)
print(normal)

[[0.54151363 0.86155509 0.50367997 0.25218648 0.29685158]
 [0.37885724 0.28652533 0.72662814 0.4990081  0.93611117]]
[[ 0.67640856  0.30861696  0.42849747 -0.34867231 -0.23560679]
 [ 0.68093003  0.52410523 -0.65337312 -0.13314533  1.06316397]]


In [7]:
e = np.arange(1,11).reshape(2,-1)
print(e)
print(e.sum(axis=1))
print(e.sum(axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[15 40]
[ 7  9 11 13 15]


In [8]:
a = np.array([1,2,3])
b = np.array([5,6,7])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 5, 6, 7])

In [9]:
a = np.array([[1,2], [3,4]])
b = np.array([5,6])
b = b[np.newaxis, :] # b는 axis가 하나이므로 a와 합치기 위해 axis를 하나 더 추가한다
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.arange(10, 20).reshape(2,-1)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[10 12 14 16 18]
 [20 22 24 26 28]]
[[-10 -10 -10 -10 -10]
 [-10 -10 -10 -10 -10]]
[[  0  11  24  39  56]
 [ 75  96 119 144 171]]
[[0.         0.09090909 0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471 0.44444444 0.47368421]]


In [11]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [12]:
a = np.arange(1,7).reshape(2,3)
print(a)
print(a.T)
print(a.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [13]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3
# broadcasting
print(test_matrix + scalar) 
print(test_matrix - scalar)
print(test_matrix * scalar)
print(test_matrix / scalar)
print(test_matrix // 0.2) # 정수 나눗셈. 소수점 나머지 버리고 정수부분만 반환한다.
print(test_matrix ** 2) # 제곱

[[4. 5. 6.]
 [7. 8. 9.]]
[[-2. -1.  0.]
 [ 1.  2.  3.]]
[[ 3.  6.  9.]
 [12. 15. 18.]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]]
[[ 4.  9. 14.]
 [19. 24. 29.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
