# Numpy

## Comparisons

In [1]:
import numpy as np

a = np.arange(10)
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [2]:
np.any(a<4)

True

In [3]:
np.all(a<5)

False

In [4]:
a = np.arange(5)
np.where(a>2, 1, -1)

array([-1, -1, -1,  1,  1])

In [5]:
np.where(a>2)

(array([3, 4], dtype=int64),)

### boolean index

In [6]:
test = np.array([1,4,0,2,3,8,9,7], float)
condition = test < 3
test[condition]

array([1., 0., 2.])

### fancy index

In [7]:
a = np.array([2,4,6,8], float)
indexes = np.array([0,0,1,3,2,1], int) # index이므로 반드시 int 타입!
a[indexes]

array([2., 2., 4., 8., 6., 4.])