# Numpy

## ndarray 생성

In [4]:
import numpy as np

In [5]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [6]:
a = np.array(a, int)
print(a)

test_array = np.array([1,4,5,"8"], float)

print(test_array)
print(type(test_array[3]))
print(test_array.dtype)
print(test_array.shape)

[1 2 3 4 5]
[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [8]:
# 3차원 배열 생성
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# 배열의 형태를 확인
print(array_3d.shape)
print(array_3d.ndim)
print(array_3d.size)

(2, 2, 2)
3
8


## Handling Shape

In [9]:
test_matrix = [[1,2,3,4],[5,6,7,8]]
np.array(test_matrix,).shape

(2, 4)

In [12]:
test_reshape = np.array(test_matrix).reshape(8,)
print(test_reshape)
test_reshape.shape

[1 2 3 4 5 6 7 8]


(8,)

In [14]:
np.array(test_matrix).reshape(-1,2).shape

(4, 2)

In [15]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

## Indexing & Slicing    

In [16]:
a = np.array([[1,2,3],[4.5,5,6]], int)
print(a)
print(a[0,0])

[[1 2 3]
 [4 5 6]]
1


In [17]:
a[0,0] = 10
print(a[0][0])

10


In [21]:
print(a[:,1:]) # 전체 행의 1열부터
print(a[1,1:3]) # 1행의 1~3열(3열은 미포함)
print(a[1:2]) # 1~2헹

[[2 3]
 [5 6]]
[5]
[[4 5 6]]


In [27]:
b = np.arange(100).reshape(10,10)
print(b)
print(b[:, -1])
b[:, ::2]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[ 9 19 29 39 49 59 69 79 89 99]


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])